site_name: ThatOSDevelopers Docs
site_description: 'Documentation for projects that ThatOSDeveloper has made.'
site_author: 'ThatOSDeveloper'
site_url: 'https://thatosdeveloper.us'

copyright: |
  &copy; ThatOSDeveloper

docs_dir: docs/

repo_name: ThatOSDeveloper/mysite
repo_url: https://github.com/ThatOSDeveloper/mysite

theme:
  name: 'material'
  
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: 'indigo'
    
  features:
  icon:
    logo: 'material/library'
    repo: 'material/library'

plugins:
  - macros

markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true

extra_javascript:
  - https://keepandroidopen.org/banner.js

extra:
  email: thatosdeveloper@thatosdeveloper.us